functionsDirectory = "/Users/venkatesh/Documents/GitHub/Truckstop Inventory Management App/frontend/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/venkatesh/Documents/GitHub/Truckstop Inventory Management App/frontend/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/venkatesh/Documents/GitHub/Truckstop Inventory Management App/frontend/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]